modLoader="javafml" #mandatory
loaderVersion="[35,)"
license="MIT"
[[mods]]
    modId="superpackutils"
    version="${file.jarVersion}}"
    displayName="SuperPack: Utils"
    issueTrackerURL="https://github.com/PufferTeam/SuperPackUtils/issues"
    displayURL="https://github.com/PufferTeam/SuperPackUtils"
    logoFile="examplemod.png"
    authors="minemobs"
    description='''Hello'''
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
[[dependencies.superpackutils]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.superpackutils]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.superpackutils]]
    modId="mekanism"
    mandatory=true
    versionRange="[10.0.18,]"
    ordering="NONE"
    side="BOTH"
[[dependencies.superpackutils]]
    modId="mrplibrary"
    mandatory=true
    versionRange="[1.16.4-1.3.4.0-forge,]"
    ordering="BEFORE"
    side="BOTH"